version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-75-238-138.eu-west-1.compute.amazonaws.com
            database: d4lk7bqgukueg1
            schema: public
            user: fbzrizpfndxith
            password: be836c5e25ecd547dfcd5ebac4a770f2004770c40780acf2f0a788f985adcadf
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true